CREATE ROLE dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
CREATE DATABASE mfdoctest_db OWNER dbuser;
-- GRANT CREATE ON DATABASE mfdoctest_db TO dbuser;
-- GRANT ALL PRIVILEGES ON DATABASE mfdoctest_db TO dbuser;
